project:
  type: website

website:
  title: "Code publishing tutorial"
  page-footer: 
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/introduction-to-renv
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: images/LMU-OSC_favicon.jpg
  margin-header: |
    ![](/images/LMU-OSC_logo.jpg){width="175"}
    
    
  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/code-publishing
          - text: Report a Bug
            url:  https://github.com/lmu-osc/code-publishing/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html

      
  sidebar:
    contents:
      - intro.qmd
      - setup.qmd
      - choose_license.qmd
      - add_readme.qmd
      - archive.qmd
      

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px



